use std::env;
use std::path::PathBuf;

fn main() {
    // Tell cargo to look for shared libraries in the specified directory
    println!("cargo:rustc-link-search=/usr/local/lib");
    
    // Tell cargo to tell rustc to link the neuromorph library if available
    if cfg!(feature = "hardware") {
        println!("cargo:rustc-link-lib=neuromorph");
    }
    
    // Generate C header file for FFI
    let crate_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    
    // Generate bindings using cbindgen
    cbindgen::Builder::new()
        .with_crate(crate_dir)
        .with_language(cbindgen::Language::C)
        .with_header("/* Generated FFI bindings for neuromorph-sys */\n#pragma once\n")
        .with_include_version(true)
        .with_autogen_warning("/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */")
        .generate()
        .expect("Unable to generate bindings")
        .write_to_file("neuromorph.h");
    
    // The bindgen::Builder is the main entry point to bindgen
    // Let it know about any headers for potential hardware libraries
    if std::path::Path::new("/usr/local/include/neuromorph.h").exists() {
        let bindings = bindgen::Builder::default()
            .header("/usr/local/include/neuromorph.h")
            .parse_callbacks(Box::new(bindgen::CargoCallbacks::new()))
            .generate()
            .expect("Unable to generate bindings");
        
        let out_path = PathBuf::from(env::var("OUT_DIR").unwrap());
        bindings
            .write_to_file(out_path.join("hardware_bindings.rs"))
            .expect("Couldn't write bindings!");
    }
}
